/* Auto-generated by sentinel_ml/energygate.py -- do not edit by hand. */
/*
 * SIMULATED -- NOT A RESULT.
 * Trained on synthetic Trace rows from ml/tests/generate_synthetic_traces.py,
 * not on real board recordings. It encodes our own assumptions about attack
 * traffic. Replace with the output of `make energygate` (ml/README.md, phase 3)
 * once real traces exist in ml/data/traces/. Never present its accuracy as a
 * measured result.
 */
#ifndef SENTINELMESH_ENERGYGATE_H
#define SENTINELMESH_ENERGYGATE_H

/* f[] must hold these 8 features, in order:
 *   f[0] = hs_per_s
 *   f[1] = hs_fail
 *   f[2] = rssi_mean
 *   f[3] = rssi_var
 *   f[4] = loss_pct
 *   f[5] = dup_pct
 *   f[6] = frag_complete_pct
 *   f[7] = battery_pct
 */
static inline float energygate_score(const float* f) {
    if (f[1] <= 4.500000f) { /* hs_fail */
        if (f[5] <= 9.984857f) { /* dup_pct */
            if (f[0] <= 1.135285f) { /* hs_per_s */
                if (f[2] <= -35.304921f) { /* rssi_mean */
                    return 0.999562f;
                } else {
                    return 0.000000f;
                }
            } else {
                if (f[1] <= 1.000000f) { /* hs_fail */
                    return 1.000000f;
                } else {
                    return 0.000000f;
                }
            }
        } else {
            if (f[4] <= 4.530091f) { /* loss_pct */
                return 0.000000f;
            } else {
                return 1.000000f;
            }
        }
    } else {
        if (f[2] <= -71.986683f) { /* rssi_mean */
            if (f[5] <= 9.805659f) { /* dup_pct */
                return 1.000000f;
            } else {
                return 0.000000f;
            }
        } else {
            return 0.000000f;
        }
    }
}

#endif /* SENTINELMESH_ENERGYGATE_H */
